config/routes.rb
Prometheus20::Application.routes.draw do
  scope '(:locale)', :locale => SUPPORTED_LOCALES do
    devise_for :users
    root :to => 'home#index'

    get 'project' => 'pages#project'

    scope '(:branch)', :branch => SUPPORTED_BRANCHES do
      resources :srpms, :id => /[^\/]+/, :only => :show do
        member do
          get 'changelog'
          get 'spec'
          get 'rawspec'
          get 'get'
          get 'gear'
        end
        resources :patches, :only => [:index, :show] do
          get 'download', :on => :member
        end
        resources :sources, :only => :index do
          get 'download', :on => :member
        end
      end
      get 'rss' => 'rss#index', :as => 'rss'
      resources :teams, :only => :show
      get 'people' => 'home#maintainers_list', :as => 'maintainers'
      get 'packages/:group(/:group2(/:group3))' => 'group#show', :as => 'group'
      get 'packages' => 'group#index', :as => 'packages'
    end

    scope 'Sisyphus', :id => /[^\/]+/ do
      get 'srpms/:id/bugs' => 'srpms#bugs', :as => 'bugs_srpm'
      get 'srpms/:id/allbugs' => 'srpms#allbugs', :as => 'allbugs_srpm'
      get 'srpms/:id/repocop' => 'srpms#repocop', :as => 'repocop_srpm'
    end

    resource :maintainer_profile, :only => [:edit, :update]
    resource :search, :only => :show, :id => /[^\/]+/
    resources :rebuild, :controller => :rebuild, :only => [:index]
    resources :rsync, :controller => :rsync, :only => [:new]

    scope ':branch', :branch => SUPPORTED_BRANCHES do
      resources :maintainers, :only => :show do
        get 'srpms', :on => :member
      end
    end

    scope 'Sisyphus' do
      get 'maintainers/:id/gear' => 'maintainers#gear', :as => 'gear_maintainer'
      get 'maintainers/:id/bugs' => 'maintainers#bugs', :as => 'bugs_maintainer'
      get 'maintainers/:id/allbugs' => 'maintainers#allbugs', :as => 'allbugs_maintainer'
      get 'maintainers/:id/ftbfs' => 'maintainers#ftbfs', :as => 'ftbfs_maintainer'
      get 'maintainers/:id/repocop' => 'maintainers#repocop', :as => 'repocop_maintainer'
    end
  end

  scope ':locale', :locale => SUPPORTED_LOCALES do
    scope ':branch', :branch => SUPPORTED_BRANCHES do
      get 'home' => 'home#index'
    end
  end

  get '(/:locale)/misc/bugs' => 'misc#bugs', :locale => SUPPORTED_LOCALES

  get '(/:locale)/:branch/security' => 'security#index', :as => 'security',
                                                         :locale => SUPPORTED_LOCALES,
                                                         :branch => SUPPORTED_BRANCHES

# TODO: drop this later
##  get '/repocop' => 'repocop#index'
##  get '/repocop/by-test/:testname' => 'repocop#bytest'
#
#  get '/repocop/by-test/install_s' => 'repocop#srpms_install_s'

  # TODO: drop this and make API
  get '/repocop/no_url_tag' => 'repocop#no_url_tag'
  get '/repocop/invalid_url' => 'repocop#invalid_url'
  get '/repocop/invalid_vendor' => 'repocop#invalid_vendor'
  get '/repocop/invalid_distribution' => 'repocop#invalid_distribution'
  get '/repocop/srpms_summary_too_long' => 'repocop#srpms_summary_too_long'
  get '/repocop/packages_summary_too_long' => 'repocop#packages_summary_too_long'
  get '/repocop/srpms_summary_ended_with_dot' => 'repocop#srpms_summary_ended_with_dot'
  get '/repocop/packages_summary_ended_with_dot' => 'repocop#packages_summary_ended_with_dot'
  get '/repocop/srpms_filename_too_long_for_joliet' => 'repocop#srpms_filename_too_long_for_joliet'
  get '/repocop/packages_filename_too_long_for_joliet' => 'repocop#packages_filename_too_long_for_joliet'
  get '/repocop/srpms_install_s' => 'repocop#srpms_install_s'
  # END

  get '/src\::name' => redirect("/en/Sisyphus/srpms/%{name}"), :name => /[^\/]+/
  get '/:name' => 'redirector#index', :name => /[^\/]+/
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @branch = Branch.where(name: params[:branch], vendor: 'ALT Linux').first
    @branches = Branch.order('order_id')
    # if !fragment_exist?("#{I18n.locale}_top15_#{@branch.name}")
    @top15 = Maintainer.top15(@branch)
    # end
    # if !fragment_exist?("#{I18n.locale}_srpms_#{@branch.name}_#{params[:page]}")
    @srpms = @branch.srpms.where("srpms.created_at > '2010-11-09 09:00:00'").includes(:branch, :builder).order('srpms.created_at DESC').page(params[:page]).per(50)
    # end
  end

  def maintainers_list
    @branch = Branch.where(name: params[:branch], vendor: 'ALT Linux').first
    @branches = Branch.order('order_id')
    @maintainers = Maintainer.order(:name)
    @teams = MaintainerTeam.order(:name)
  end
end

app/views/home/_srpms.html.erb
<%# cache("#{I18n.locale}_srpms_#{@branch.name}_#{params[:page]}") do %>
<% @srpms.each do |srpm| %>
  <span class="news-date-new">
    <%= link_to "#{srpm.name}-#{srpm.version}-#{srpm.release}", srpm_path(srpm.branch, srpm), class: 'news', title: _('detailed information about the package') %>
  </span>

  <% if srpm.builder %>
  <span class="news-text" style="border-bottom: dotted 1px #f0f0f0">&nbsp;<%= _('build') %>
    <%= link_to _(srpm.builder.name), maintainer_path(srpm.branch, srpm.builder), class: 'news', title: _('information about maintainer') %>, <%= srpm.buildtime %>
  </span>
  <% else %>
  <span class="news-text" style="border-bottom: dotted 1px #f0f0f0">&nbsp;<%= _('build') %>
    <%= srpm.buildtime %>
  </span>
  <% end %>

  <div id="pkg-<%= srpm.name %>" style="display:block;margin-top:1em;">
    <b><%= _('Group:') %></b> <span class="news-text"><%= _(srpm.groupname) %></span><br>
    <b><%= _('Summary:') %></b> <span class="news-text"><%= srpm.summary %></span><br>
    <b><%= _('Changes:') %></b> <div class="para"><%= simple_format(srpm.changelogtext) %></div>
  </div>
  <p class="news" />

<% end %>

<p class="break" />
  <div style="text-align:center">
    <%= paginate @srpms %>
  </div>
</div>

<%# end %>

app/views/home/_top15.html.erb
<%# cache("#{I18n.locale}_top15_#{@branch.name}") do %>
  <% @top15.each do |maintainer| %>
    <tr>
      <td style='text-align: left;'>
        <%= link_to _(maintainer[1]), maintainer_path('Sisyphus', maintainer[0]), class: 'news', title: _('information about maintainer') %>
      </td>
      <td style='text-align: right;'><%= maintainer[2] %></td>
    </tr>
  <% end %>
<%# end %>

app/views/home/index.html.erb
<% title _("Prometheus 2.0 - Intro") %>
<% description _('ALT Linux Team - Sisyphus packages info') %>

<div id='main-content'>

<div class="header">Sisyphus</div>
<p style="text-align: justify;">
<span class="news-text">
<%= raw _("<b>Sisyphus</b> is daily updated free software repository by <abbr title=\"Independent ALT Linux development team\" style=\"border-bottom: 1px dotted gray;\">ALT&nbsp;Linux&nbsp;Team</abbr>. Participation in Sisyphus project is open for anyone. This project is based upon software packaging and dependency tracking technologies as well as robust developer collaboration processes. Any ALT&nbsp;Linux distribution and <b>APT</b> package manager is sufficient to use Sisyphus. Sisyphus is a solution set constantly being under development which can be used to create universal or specialized <b>Linux distributions</b> or just <b>single systems</b>.") %>
<br><br>
<%= raw _("Any ALT&nbsp;Linux distribution and <b>APT</b> package manager is sufficient to use Sisyphus <b><a href=\"http://en.altlinux.org/Regular\">regular LiveCD builds</a></b>.") %>
<br><br>
<%= _('Sisyphus is not intended for end users and its usage may result in unpredictable behaviour. You might want to use ALT Linux distributions and their usual updates if you want to run a reliable system.') %>
</span>
</p>
<p class="break" />

<p class="news" />
<div class="header"><%= _('New SRPMs') %></div>
<p class="news" />

<%= render partial: 'srpms' %>

<div id="bottom-offset-l"><div id="bottom-offset-r">&nbsp;</div></div><div id="rightbar">
  <div class="headleft">
    <div class="headright" title="<%= _('sort maintainers by amount of packages') %>">
      <%= _("TOP maintainers") %>
    </div>
    <%= image_tag('collapse.gif', id: 'topMain', class: 'close', title: _('hide window'), alt: _('hide window'), size: '10x9') %>
  </div>
  <div id="topMainDiv" style="border: dotted #aabccd 1px;margin: 0px 4px 4px 4px;">
  <table style="font-size:8pt;" width="100%">
    <%= render partial: 'top15' %>
    <tr><td colspan="2" align="center">&hellip;</td></tr>
  </table>
</div><br>
    <div class="headleft">
      <div class="headright" title="<%= _('sort packages by amount of releases in the last half of year') %>">
        <%= _('TOP RPMs') %>
      </div>
      <%= image_tag('collapse.gif', id: 'topRPM', class: 'close', title: _('hide window'), alt: _('hide window'), size: '10x9') %>
    </div>
  <div id="topRPMDiv" style="border: dotted gray 1px;margin: 0px 4px 4px 4px;">
  <table style="font-size:8pt;" width="100%">
<!--#include virtual="/cgi-bin/stats.pl?type=activity" -->
  <tr><td colspan="2" align="center">&hellip;</td></tr>
  </table>
</div><br>
    <div class="headleft">
      <div class="headright" title="<%= _('tips and tricks') %>">
        <%= raw _('tips &amp; tricks') %>
      </div>
      <%= image_tag('collapse.gif', id: 'topTips', class: 'close', title: _('hide window'), alt: _('hide window'), size: '10x9') %>
    </div>
    <div id="topTipsDiv" style="border: dotted gray 1px;margin: 0px 4px 4px 4px; text-align: justify;padding:2px">
      <b><%= _('Sisyphus sync') %></b><br><%= raw _('<b>Q:</b> How can I skip heap of packages if I even don\'t know why I need them?') %><br><%= raw _('<b>A:</b> Create filter for rsync with the help of this') %> <%= link_to _('form'), new_rsync_path, class: 'news' %>
    </div><br>
    <div class="headleft">
      <div class="headright" title="<%= _('select branch') %>">
        <%= _('Select branch:') %>
      </div>
      <%= image_tag('collapse.gif', id: 'topBranches', class: 'close', title: _('hide window'), alt: _('hide window'), size: '10x9') %>
    </div>
    <div id="topBranchesDiv" style="border: dotted gray 1px;margin: 0px 4px 4px 4px; text-align: justify;padding:2px">
      <table style="font-size:8pt;" width="100%">
      <% @branches.each do |branch| %>
          <tr>
            <td style="text-align: left;">
              <%= link_to branch.name, home_path(branch: branch.name), class: 'news', title: _('switch branch to it') %>
            </td>
            <td style="text-align: right;"><%= branch.srpms.count(:all) %></td>
          </tr>
      <% end %>
    </table>
    </div>
</div>

<!--#include virtual="/inc/bottom.shtml?skipit" -->

app/views/home/maintainers_list.html.erb
<% title _('Prometheus 2.0 - Maintainers &amp; Teams') %>

<div id='main-content'>

<div id="rightbar">
<div class="headleft">
<div class="headright" title="<%= _('ALT Linux repositories') %>">
  <%= _('ALT Linux repositories') %>
</div>
<%= image_tag('collapse.gif', id: 'topRPM', class: 'close', title: _('hide window'), alt: _('hide window'), size: '10x9') %>
</div>
<div id="topRPMDiv" style="border: dotted gray 1px; margin: 0px 4px 4px 4px;">
<table style="font-size:8pt;" width="100%">

<% @branches.each do |branch| %>
<tr>
  <td style="text-align: left;">
    <%= link_to branch.name, maintainers_path(branch), class: 'news' %>
  </td>
  <td style="text-align: right;"><%= branch.counter.value %></td>
</tr>
<% end %>

</table>
</div>
</div>

  <table style='font-size: 10pt;' width='100%'>
    <tr>
      <th><%= _('Maintainers') %></th>
      <th><%= _('Teams') %></th>
    </tr>
    <tr>
      <td valign='top'>
        <% @maintainers.each do |maintainer| %>
          <% if $redis.smembers("#{@branch.name}:maintainers:#{maintainer.login}").count > 0 %>
          <div style='margin-bottom: 2px; text-align: left; border-bottom: 1px gray dotted; width: 95%; font-size: 9pt; height: 10pt;'>
            <div style='float: left;'>
              <%= link_to _(maintainer.name), maintainer_path(@branch, maintainer),
                          class: 'news', title: _('information about maintainer') %>
              <%= link_to " (#{maintainer.login})", maintainer_path(@branch, maintainer), style: 'text-decoration: none; color: black;' %>
            </div>
            <div style='float: right;'><%= $redis.smembers("#{@branch.name}:maintainers:#{maintainer.login}").count %></div>
          </div>
          <% end %>
        <% end %>
      </td>
      <td valign='top'>
        <% @teams.each do |team| %>
          <% if $redis.smembers("#{@branch.name}:maintainers:#{team.login}").count > 0 %>
          <div style='margin-bottom: 2px; text-align: left; border-bottom: 1px gray dotted; width: 95%; font-size: 9pt; height: 10pt;'>
            <div style='float: left;'>
              <%= link_to team.name, team_path(id: team.login[1..-1], branch: @branch.name), class: 'news' %>
              <%= link_to " (#{team.login[1..-1]})", team_path(id: team.login[1..-1], branch: @branch.name), style: 'text-decoration: none; color: black;' %>
            </div>
            <div style='float: right;'><%= $redis.smembers("#{@branch.name}:maintainers:#{team.login}").count %></div>
          </div>
          <% end %>
        <% end %>
      </td>
    </tr>
  </table>
</div>

<div id='bottom-offset-l'>
  <div id='bottom-offset-r'>
    &nbsp;
  </div>
</div>

app/views/home/packagers_list.html.erb
<% title _("Prometheus 2.0 - Maintainers") %>
<% url "/people" %>

<table width="100%" style="font-size:10pt;">
<tr><th><%= _("Maintainers") %></th><th><%= _("Teams") %></th></tr>
<tr>
<td valign="top">
<% @packagers.each do |packager| -%>
  <div style="margin-bottom: 2px;text-align:left;border-bottom: 1px gray dotted; width: 95%; font-size: 9pt; height: 10pt">
    <div style="float:left">
      <%= link_to packager.name, '/' + params[:locale] + '/packager/' + packager.login, :class => 'news' %> (<%= packager.login %>)
    </div>
    <div style="float:right"> <%= packager.counter %></div>
  </div>
<% end -%>
</td>
<td valign="top">
<% @teams.each do |team| -%>
  <div style="margin-bottom: 2px;text-align:left;border-bottom: 1px gray dotted; width: 95%; font-size: 9pt; height: 10pt">
    <div style="float:left">
      <%= link_to team.name, '/' + params[:locale] + '/team/' + team.login[1..-1], :class => 'news' %> (<%= team.login[1..-1] %>)
    </div>
    <div style="float:right"> <%= team. counter %></div>
  </div>
<% end -%>
</td>
</tr>
</table>

</div><div id="bottom-offset-l"><div id="bottom-offset-r">&nbsp;</div></div>