config/routes.rb
Prometheus20::Application.routes.draw do
  scope '(:locale)', :locale => SUPPORTED_LOCALES do
    devise_for :users
    root :to => 'home#index'

    get 'project' => 'pages#project'

    scope '(:branch)', :branch => SUPPORTED_BRANCHES do
      resources :srpms, :id => /[^\/]+/, :only => :show do
        member do
          get 'changelog'
          get 'spec'
          get 'rawspec'
          get 'get'
          get 'gear'
        end
        resources :patches, :only => [:index, :show] do
          get 'download', :on => :member
        end
        resources :sources, :only => :index do
          get 'download', :on => :member
        end
      end
      get 'rss' => 'rss#index', :as => 'rss'
      resources :teams, :only => :show
      get 'people' => 'home#maintainers_list', :as => 'maintainers'
      get 'packages/:group(/:group2(/:group3))' => 'group#show', :as => 'group'
      get 'packages' => 'group#index', :as => 'packages'
    end

    scope 'Sisyphus', :id => /[^\/]+/ do
      get 'srpms/:id/bugs' => 'srpms#bugs', :as => 'bugs_srpm'
      get 'srpms/:id/allbugs' => 'srpms#allbugs', :as => 'allbugs_srpm'
      get 'srpms/:id/repocop' => 'srpms#repocop', :as => 'repocop_srpm'
    end

    resource :maintainer_profile, :only => [:edit, :update]
    resource :search, :only => :show, :id => /[^\/]+/
    resources :rebuild, :controller => :rebuild, :only => [:index]
    resources :rsync, :controller => :rsync, :only => [:new]

    scope ':branch', :branch => SUPPORTED_BRANCHES do
      resources :maintainers, :only => :show do
        get 'srpms', :on => :member
      end
    end

    scope 'Sisyphus' do
      get 'maintainers/:id/gear' => 'maintainers#gear', :as => 'gear_maintainer'
      get 'maintainers/:id/bugs' => 'maintainers#bugs', :as => 'bugs_maintainer'
      get 'maintainers/:id/allbugs' => 'maintainers#allbugs', :as => 'allbugs_maintainer'
      get 'maintainers/:id/ftbfs' => 'maintainers#ftbfs', :as => 'ftbfs_maintainer'
      get 'maintainers/:id/repocop' => 'maintainers#repocop', :as => 'repocop_maintainer'
    end
  end

  scope ':locale', :locale => SUPPORTED_LOCALES do
    scope ':branch', :branch => SUPPORTED_BRANCHES do
      get 'home' => 'home#index'
    end
  end

  get '(/:locale)/misc/bugs' => 'misc#bugs', :locale => SUPPORTED_LOCALES

  get '(/:locale)/:branch/security' => 'security#index', :as => 'security',
                                                         :locale => SUPPORTED_LOCALES,
                                                         :branch => SUPPORTED_BRANCHES

# TODO: drop this later
##  get '/repocop' => 'repocop#index'
##  get '/repocop/by-test/:testname' => 'repocop#bytest'
#
#  get '/repocop/by-test/install_s' => 'repocop#srpms_install_s'

  # TODO: drop this and make API
  get '/repocop/no_url_tag' => 'repocop#no_url_tag'
  get '/repocop/invalid_url' => 'repocop#invalid_url'
  get '/repocop/invalid_vendor' => 'repocop#invalid_vendor'
  get '/repocop/invalid_distribution' => 'repocop#invalid_distribution'
  get '/repocop/srpms_summary_too_long' => 'repocop#srpms_summary_too_long'
  get '/repocop/packages_summary_too_long' => 'repocop#packages_summary_too_long'
  get '/repocop/srpms_summary_ended_with_dot' => 'repocop#srpms_summary_ended_with_dot'
  get '/repocop/packages_summary_ended_with_dot' => 'repocop#packages_summary_ended_with_dot'
  get '/repocop/srpms_filename_too_long_for_joliet' => 'repocop#srpms_filename_too_long_for_joliet'
  get '/repocop/packages_filename_too_long_for_joliet' => 'repocop#packages_filename_too_long_for_joliet'
  get '/repocop/srpms_install_s' => 'repocop#srpms_install_s'
  # END

  get '/src\::name' => redirect("/en/Sisyphus/srpms/%{name}"), :name => /[^\/]+/
  get '/:name' => 'redirector#index', :name => /[^\/]+/
end

app/models/srpm.rb
class Srpm < ActiveRecord::Base
  belongs_to :branch
  belongs_to :group

  validates :branch, presence: true
  validates :group, presence: true
  validates :groupname, presence: true
  validates :md5, presence: true

  has_many :packages, dependent: :destroy
  has_many :changelogs, dependent: :destroy
  has_one :specfile, dependent: :destroy
  has_many :patches, dependent: :destroy
  has_many :sources, dependent: :destroy

  has_many :repocops, foreign_key: 'srcname', primary_key: 'name'
  has_one :repocop_patch, foreign_key: 'name', primary_key: 'name'

  has_one :builder, class_name: 'Maintainer', foreign_key: 'id',
                    primary_key: 'builder_id'

  after_create :increment_branch_counter
  after_destroy :decrement_branch_counter

  def to_param
    name
  end

  def acls
    if $redis.exists("#{self.branch.name}:#{self.name}:acls")
      Maintainer.where(login: $redis.smembers("#{self.branch.name}:#{self.name}:acls")).order(:name).select('login').map(&:login).join(',')
    else
      nil
    end
  end

  def self.import(branch, file)
    srpm = Srpm.new
    srpm.name = `export LANG=C && rpm -qp --queryformat='%{NAME}' #{file}`
    srpm.version = `export LANG=C && rpm -qp --queryformat='%{VERSION}' #{file}`
    srpm.release = `export LANG=C && rpm -qp --queryformat='%{RELEASE}' #{file}`
    srpm.epoch = `export LANG=C && rpm -qp --queryformat='%{EPOCH}' #{file}`
    # TODO: make test for this
    srpm.epoch = nil if srpm.epoch == '(none)'
    srpm.filename = "#{srpm.name}-#{srpm.version}-#{srpm.release}.src.rpm"

    group_name = `export LANG=C && rpm -qp --queryformat='%{GROUP}' #{file}`
    Group.import(branch, group_name)
    group = Group.in_branch(branch, group_name)

    Maintainer.import(`export LANG=C && rpm -qp --queryformat='%{PACKAGER}' #{file}`)

    srpm.group_id = group.id
    srpm.groupname = group_name
    srpm.summary = `export LANG=C && rpm -qp --queryformat='%{SUMMARY}' #{file}`
    # TODO: test for this
    # hack for very long summary in openmoko_dfu-util src.rpm
    srpm.summary = 'Broken' if srpm.name == 'openmoko_dfu-util'
    srpm.license = `export LANG=C && rpm -qp --queryformat='%{LICENSE}' #{file}`
    srpm.url = `export LANG=C && rpm -qp --queryformat='%{URL}' #{file}`
    # TODO: make test for this
    srpm.url = nil if srpm.url == '(none)'
    srpm.description = `export LANG=C && rpm -qp --queryformat='%{DESCRIPTION}' #{file}`
    srpm.vendor = `export LANG=C && rpm -qp --queryformat='%{VENDOR}' #{file}`
    srpm.distribution = `export LANG=C && rpm -qp --queryformat='%{DISTRIBUTION}' #{file}`
    srpm.buildtime = Time.at(`export LANG=C && rpm -qp --queryformat='%{BUILDTIME}' #{file}`.to_i)
    srpm.size = File.size(file)
    srpm.md5 = `/usr/bin/md5sum #{file}`.split[0]
    srpm.branch_id = branch.id
    srpm.changelogtime = Time.at(`export LANG=C && rpm -qp --queryformat='%{CHANGELOGTIME}' #{file}`.to_i)

    changelogname = `export LANG=C && rpm -qp --queryformat='%{CHANGELOGNAME}' #{file}`
    srpm.changelogname = changelogname

    srpm.changelogtext = `export LANG=C && rpm -qp --queryformat='%{CHANGELOGTEXT}' #{file}`

    email = srpm.changelogname.chop.split('<')[1].split('>')[0] rescue nil

    if email
      email.downcase!
      email = Maintainer.new.fix_maintainer_email(email)
      Maintainer.import_from_changelogname(changelogname)
      maintainer = Maintainer.where(email: email).first
      srpm.builder_id = maintainer.id
    end

    if srpm.save
      $redis.set("#{branch.name}:#{srpm.filename}", 1)
      Changelog.import(branch, file, srpm)
      Specfile.import(branch, file, srpm)
      Patch.import(branch, file, srpm)
      Source.import(branch, file, srpm)
    else
      puts "#{Time.now.to_s}: failed to update '#{srpm.filename}'"
    end
  end

  def self.import_all(branch, path)
    Dir.glob(path).each do |file|
      unless $redis.exists("#{branch.name}:#{File.basename(file)}")
        next unless File.exist?(file)
        next unless Rpm.check_md5(file)
        puts "#{Time.now.to_s}: import '#{File.basename(file)}'"
        Srpm.import(branch, file)
      end
    end
  end

  def self.remove_old(branch, path)
    branch.srpms.each do |srpm|
      unless File.exists?("#{path}#{srpm.filename}")
        srpm.packages.each do |package|
          puts "#{Time.now.to_s}: delete '#{package.filename}' from redis cache"
          $redis.del("#{branch.name}:#{package.filename}")
        end
        puts "#{Time.now.to_s}: delete '#{srpm.filename}' from redis cache"
        $redis.del("#{branch.name}:#{srpm.filename}")
        puts "#{Time.now.to_s}: delete acls for '#{srpm.filename}' from redis cache"
        $redis.del("#{branch.name}:#{srpm.name}:acls")
        $redis.del("#{branch.name}:#{srpm.name}:leader")
        srpm.destroy
      end
    end
  end

  def self.contributors(branch, srpm)
    logins = []
    branch.srpms.where(name: srpm.name).first.changelogs.each do |changelog|
      name = changelog.changelogname.split('<')[0].chomp
      name.strip!
      email = changelog.changelogname.chop.split('<')[1]
      next if email.nil?
      email.downcase!
      email = Maintainer.new.fix_maintainer_email(email)
      login = email.split('@')[0]
      logins << login
    end
    Maintainer.where(login: logins.sort.uniq).order(:name)
  end

  private

  def increment_branch_counter
    branch.counter.increment
  end

  def decrement_branch_counter
    branch.counter.decrement
  end
end

app/controllers/api/v1/srpms_controller.rb
class Api::V1::SrpmsController < ApplicationController
  def srpms_list
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpms = @branch.srpms.order(:name).select(:name)
  end

  def show
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).first
  end

  def changelog
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).first
    @changelogs = @srpm.changelogs.order('changelogs.created_at ASC')
  end

  def gear
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).first
    @gears = Gear.where(repo: params[:id]).order('lastchange DESC')
  end

  def bugs
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).first
    names = @srpm.packages.map { |package| package.name }.flatten.sort.uniq
    @bugs = Bug.where(component: names, bug_status: ['NEW', 'ASSIGNED', 'VERIFIED', 'REOPENED']).order('bug_id DESC')
  end

  def allbugs
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).first
    names = @srpm.packages.map { |package| package.name }.flatten.sort.uniq
    @allbugs = Bug.where(component: names).order('bug_id DESC')
  end

  def repocop
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).first
    @repocops = Repocop.where(srcname: @srpm.name,
                              srcversion: @srpm.version,
                              srcrel: @srpm.release)
  end
end

app/controllers/srpms_controller.rb
class SrpmsController < ApplicationController
  def show
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).includes(:packages, :branch).first
    render status: 404, action: 'nosuchpackage' and return unless @srpm

    @ftbfs = @branch.ftbfs.where(name: @srpm.name,
                                 version: @srpm.version,
                                 release: @srpm.release,
                                 epoch: @srpm.epoch).select('DISTINCT id, arch, weeks')
    @contributors = Srpm.contributors(@branch, @srpm)
    if @srpm.name[0..4] == 'perl-' && @srpm.name != 'perl'
      @perl_watch = PerlWatch.where(name: @srpm.name[5..-1].gsub('-', '::')).first
    end
    @allsrpms = Srpm.where(name: params[:id]).includes(:branch).order('branches.order_id')
    if $redis.exists("#{@branch.name}:#{@srpm.name}:acls")
      @maintainers = Maintainer.where(login: $redis.smembers("#{@branch.name}:#{@srpm.name}:acls").reject{|acl| acl[0] == '@'}).order(:name)
      @teams = MaintainerTeam.where(login: $redis.smembers("#{@branch.name}:#{@srpm.name}:acls").reject{|acl| acl[0] != '@'}).order(:name)
    end
    if $redis.exists("#{@branch.name}:#{@srpm.name}:leader")
      login = $redis.get("#{@branch.name}:#{@srpm.name}:leader")
      if login[0] == '@'
        @leader = MaintainerTeam.where(login: login).first
      else
        @leader = Maintainer.where(login: login).first
      end
    end
  end

  def changelog
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).includes(:branch).first
    render status: 404, action: 'nosuchpackage' and return unless @srpm
    @changelogs = @srpm.changelogs.order('changelogs.created_at ASC')
    @allsrpms = Srpm.where(name: params[:id]).includes(:branch).order('branches.order_id')
  end

  def spec
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).includes(:branch).first
    render status: 404, action: 'nosuchpackage' and return unless @srpm
    @allsrpms = Srpm.where(name: params[:id]).includes(:branch).order('branches.order_id')
  end

  def rawspec
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).includes(:group, :branch).first
    render status: 404, action: 'nosuchpackage' and return unless @srpm
    if @srpm.specfile
      send_data @srpm.specfile.spec, disposition: 'attachment', type: 'text/plain', filename: "#{@srpm.name}.spec"
    else @srpm.specfile.nil?
      render layout: false
    end
  end

  def get
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @mirrors = Mirror.where(branch_id: @branch).where("protocol != 'rsync'").order('mirrors.order_id ASC')
    @srpm = @branch.srpms.where(name: params[:id]).includes(:branch).first
    render status: 404, action: 'nosuchpackage' and return unless @srpm

    @allsrpms = Srpm.where(name: params[:id]).includes(:branch).order('branches.order_id')
    @i586 = @srpm.packages.where(arch: 'i586').order('packages.name ASC')
    @noarch = @srpm.packages.where(arch: 'noarch').order('packages.name ASC')
    @x86_64 = @srpm.packages.where(arch: 'x86_64').order('packages.name ASC')
    @arm = @srpm.packages.where(arch: 'arm').order('packages.name ASC')
  end

  def gear
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).includes(:branch).first
    render status: 404, action: 'nosuchpackage' and return unless @srpm

    # TODO: use srpm_id !
    @gears = Gear.where(repo: params[:id]).includes(:maintainer).order('lastchange DESC')
  end

  def bugs
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).includes(:branch).first
    render status: 404, action: 'nosuchpackage' and return unless @srpm

    names = @srpm.packages.map { |package| package.name }.flatten.sort.uniq

    @bugs = Bug.where(component: names, bug_status: ['NEW', 'ASSIGNED', 'VERIFIED', 'REOPENED']).order('bug_id DESC')
    @allbugs = Bug.where(component: names).order('bug_id DESC')
  end

  def allbugs
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).includes(:branch).first
    render status: 404, action: 'nosuchpackage' and return unless @srpm

    names = @srpm.packages.map { |package| package.name }.flatten.sort.uniq

    @bugs = Bug.where(component: names, bug_status: ['NEW', 'ASSIGNED', 'VERIFIED', 'REOPENED']).order('bug_id DESC')
    @allbugs = Bug.where(component: names).order('bug_id DESC')
  end

  def repocop
    @branch = Branch.find_by_name_and_vendor!(params[:branch], 'ALT Linux')
    @srpm = @branch.srpms.where(name: params[:id]).includes(:branch).first
    render status: 404, action: 'nosuchpackage' and return unless @srpm
    @repocops = Repocop.where(srcname: @srpm.name,
                              srcversion: @srpm.version,
                              srcrel: @srpm.release)
  end
end

app/helpers/srpms_helper.rb
module SrpmsHelper
  def colorize_specfile(text)
    text.force_encoding('UTF-8')
    text = text.gsub('@altlinux', ' at altlinux')

    # ${$text}=~ s/&/&amp;/g;
    # ${$text}=~ s/>/&gt;/g;
    # ${$text}=~ s/</&lt;/g;
    # ${$text}=~ s/\"/&quot;/g;
    text = ERB::Util.h(text)

    # ${$text}=~ s/\@/ at /g;

    # ${$text}=~ s/(Url\:\s+)(((http|ftp)\:\/\/[^\s\[\]]{1,100})([^\s\]\[]*))/"$1".&linkme($2,$3,$5)/gie;
    # TODO: add link to Url:

    # ${$text}=~ s/^(\w+\:)/<b>$1<\/b>/g;
    text = text.gsub(/^(\w+\:)/) { |s| s = "<b>#{s}</b>" }

    text = text.gsub(/\t/, '&nbsp;' * 8)
    text = text.gsub(' ', '&nbsp;')

    # ${$text}=~ s/^(\s*\#.*)/<b class='comment'>$1<\/b>/g;
    # text = text.gsub(/^(\s*\#.*)/) { |s| s = "<b class='comment'>#{s}</b>" }

    # ${$text}=~ s/\n([\w\(\)\-\.]+\:)/\n<b>$1<\/b>/g;
    text = text.gsub(/\n([\w\(\)\-\.]+\:)/) { |s| s = "<b>#{s}</b>" }

    # ${$text}=~ s/\n(\s*\#.*)/\n<b class='comment'>$1<\/b>/g;

    text = text.gsub(/(\s*\#.*)/) { |s| s = "<b class='comment'>#{s}</b>" }

    # ${$text}=~ s/\n\%(description|prep|build|install|preun|pre|postun|post|triggerpostun|trigger|files|changelog|package)([\n|\s])/\n<b class='reserved'>\%$1<\/b>$2/g;
    text = text.gsub(/^%(description|prep|build|check|install|preun|pre|postun|post|triggerpostun|trigger|files|changelog|package)/) { |s| s = "<b class='reserved'>#{s}</b>" }

    # ${$text}=~ s/\n/<br \/>/g;
    text = text.gsub(/\n/, '<br>')

    # ${$text}=~ s/\r//g;
    text = text.gsub(/\r/, '')

    text.html_safe
    text
  end
end

app/views/srpms/_leader.html.erb
<% if leader %>
  <div class="maintainer"><b><%= _('Current maintainer:') %></b>
    <% if leader.class.to_s == 'MaintainerTeam' %>
      <%= link_to leader.name, team_path(branch, leader.login[1..-1]),
                  class: 'news', title: _('information about maintainer') %>
    <% else %>
      <%= link_to _(leader.name), maintainer_path(branch, leader),
                  class: 'news', title: _('information about maintainer') %>
    <% end %>
  </div>

  <br>
<% end %>

app/views/srpms/changelog.html.erb
<% title _('Prometheus 2.0 - Package &laquo;%s&raquo; - Changelog') % @srpm.name %>
<% description "#{@srpm.name} - #{@srpm.summary}" %>
<% keywords @srpm.summary %>

<div id='main-content'>

<div id="rightbar">
<div class="headleft">
<div class="headright" title="<%= _('ALT Linux repositories') %>">
  <%= _('ALT Linux repositories') %>
</div>
<%= image_tag('collapse.gif', id: 'topRPM', class: 'close', title: _('hide window'), alt: _('hide window'), size: '10x9') %>
</div>
<div id="topRPMDiv" style="border: dotted gray 1px;margin: 0px 4px 4px 4px;">
<table style="font-size:8pt;" width="100%">

<% @allsrpms.each do |rpm| %>
<tr>
  <td style="text-align: left;">
    <%= link_to "#{rpm.branch.name}:", changelog_srpm_path(id: rpm.name, branch: rpm.branch.name), class: 'news' %>
  </td>
  <td style="text-align: right;"><%= "#{rpm.version}-#{rpm.release}" %></td>
</tr>
<% end %>

</table>
</div><br>
</div>

<div style="height:3em;">
  <div id="rpmtop">
    <b style="font-size:9pt;"><%= _('Group') %> :: <%= _(@srpm.groupname) %></b><br>
    <div class="header" style="letter-spacing:1px;"><%= _('Source RPM:') %> <%= @srpm.name %></div>
  </div>
</div>

<div>
<p class="break" />
<span class="vkladka">&nbsp;<%= link_to _('Main'), srpm_path(@srpm.branch, @srpm), class: 'news', title: _('information about SRPM') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="current">&nbsp;<b><%= _('Changelog') %></b>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Spec'), spec_srpm_path(@srpm.branch, @srpm), class: 'news', title: _('spec') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Patches'), srpm_patches_path(@srpm.branch, @srpm), class: 'news', title: _('patches') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Sources'), srpm_sources_path(@srpm.branch, @srpm), class: 'news', title: _('sources') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Download'), get_srpm_path(@srpm.branch, @srpm), class: 'news', title: _('download latest version') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Gear'), gear_srpm_path(@srpm.branch, @srpm), class: 'news', title: _('this package in gear repositories') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Bugs and FR'), bugs_srpm_path(@srpm), class: 'news', title: _('list of bugs and feature requests') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Repocop'), repocop_srpm_path(@srpm), class: 'news', title: _('repocop bugreports') %>&nbsp;</span><p class="news" />

<% @changelogs.each do |changelog| %>
  <% if changelog.changelogname.force_encoding("UTF-8").valid_encoding? &&
        changelog.changelogtext.force_encoding("UTF-8").valid_encoding? %>
  <p class="news" />
  <b><%= Time.at(changelog.changelogtime.to_i).to_date %> <%= changelog.changelogname.gsub('@altlinux', ' at altlinux').gsub('@', ' at ') %></b> <br>
  <ul class="change">
    <%= simple_format(changelog.changelogtext) %>
  </ul>
  <% else %>
  <p class="news" />
    <b><%= _('Broken changelog entry.') %></b>
  <% end%>
<% end %>

</div>

</div><div id="bottom-offset-l"><div id="bottom-offset-r">&nbsp;</div></div>

app/views/srpms/rawspec.html.erb
<%= _('Spec file not yet imported.') %>

app/views/srpms/spec.html.erb
<% title _('Prometheus 2.0 - Package &laquo;%s&raquo; - Spec') % @srpm.name %>
<% description "#{@srpm.name} - #{@srpm.summary}" %>
<% keywords @srpm.summary %>

<div id='main-content'>
  <div id='rightbar'>
    <%= render 'allsrpms_spec', allsrpms: @allsrpms %>
  </div>

  <%= render 'group', srpm: @srpm %>

<div>
<p class="break" />
<span class="vkladka">&nbsp;<%= link_to _('Main'), srpm_path(@srpm.branch, @srpm), :class => 'news', :title => _('information about SRPM') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Changelog'), changelog_srpm_path(@srpm.branch, @srpm), :class => 'news', :title => _('full changelog') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="current">&nbsp;<b><%= _('Spec') %></b>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Patches'), srpm_patches_path(@srpm.branch, @srpm), :class => 'news', :title => _('patches') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Sources'), srpm_sources_path(@srpm.branch, @srpm), :class => 'news', :title => _('sources') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Download'), get_srpm_path(@srpm.branch, @srpm), :class => 'news', :title => _('download latest version') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Gear'), gear_srpm_path(@srpm.branch, @srpm), :class => 'news', :title => _('this package in gear repositories') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Bugs and FR'), bugs_srpm_path(@srpm), :class => 'news', :title => _('list of bugs and feature requests') %>&nbsp;</span><span class="underl">&nbsp;</span><span class="vkladka">&nbsp;<%= link_to _('Repocop'), repocop_srpm_path(@srpm), :class => 'news', :title => _('repocop bugreports') %>&nbsp;</span><p class="news" />

<% if @srpm.specfile %>
<%= link_to _('Raw spec file'), rawspec_srpm_path(@srpm.branch, @srpm), class: 'news', title: _('Raw spec file') %>

<br><br>

<% if @srpm.specfile.spec.force_encoding("UTF-8").valid_encoding? %>
  <%#= simple_format h(@srpm.specfile.spec.force_encoding("UTF-8").gsub('@altlinux', ' at altlinux')) %>
  <%= raw colorize_specfile @srpm.specfile.spec %>
<% else %>
  <%= _('Specfile is not UTF-8 valid.') %>
<% end %>

<% else %>
No imported yet.
<% end %>
</div>

</div>

<div id="bottom-offset-l">
  <div id="bottom-offset-r">
    &nbsp;
  </div>
</div>