config/routes.rb
Prometheus20::Application.routes.draw do
  scope '(:locale)', :locale => SUPPORTED_LOCALES do
    devise_for :users
    root :to => 'home#index'

    get 'project' => 'pages#project'

    scope '(:branch)', :branch => SUPPORTED_BRANCHES do
      resources :srpms, :id => /[^\/]+/, :only => :show do
        member do
          get 'changelog'
          get 'spec'
          get 'rawspec'
          get 'get'
          get 'gear'
        end
        resources :patches, :only => [:index, :show] do
          get 'download', :on => :member
        end
        resources :sources, :only => :index do
          get 'download', :on => :member
        end
      end
      get 'rss' => 'rss#index', :as => 'rss'
      resources :teams, :only => :show
      get 'people' => 'home#maintainers_list', :as => 'maintainers'
      get 'packages/:group(/:group2(/:group3))' => 'group#show', :as => 'group'
      get 'packages' => 'group#index', :as => 'packages'
    end

    scope 'Sisyphus', :id => /[^\/]+/ do
      get 'srpms/:id/bugs' => 'srpms#bugs', :as => 'bugs_srpm'
      get 'srpms/:id/allbugs' => 'srpms#allbugs', :as => 'allbugs_srpm'
      get 'srpms/:id/repocop' => 'srpms#repocop', :as => 'repocop_srpm'
    end

    resource :maintainer_profile, :only => [:edit, :update]
    resource :search, :only => :show, :id => /[^\/]+/
    resources :rebuild, :controller => :rebuild, :only => [:index]
    resources :rsync, :controller => :rsync, :only => [:new]

    scope ':branch', :branch => SUPPORTED_BRANCHES do
      resources :maintainers, :only => :show do
        get 'srpms', :on => :member
      end
    end

    scope 'Sisyphus' do
      get 'maintainers/:id/gear' => 'maintainers#gear', :as => 'gear_maintainer'
      get 'maintainers/:id/bugs' => 'maintainers#bugs', :as => 'bugs_maintainer'
      get 'maintainers/:id/allbugs' => 'maintainers#allbugs', :as => 'allbugs_maintainer'
      get 'maintainers/:id/ftbfs' => 'maintainers#ftbfs', :as => 'ftbfs_maintainer'
      get 'maintainers/:id/repocop' => 'maintainers#repocop', :as => 'repocop_maintainer'
    end
  end

  scope ':locale', :locale => SUPPORTED_LOCALES do
    scope ':branch', :branch => SUPPORTED_BRANCHES do
      get 'home' => 'home#index'
    end
  end

  get '(/:locale)/misc/bugs' => 'misc#bugs', :locale => SUPPORTED_LOCALES

  get '(/:locale)/:branch/security' => 'security#index', :as => 'security',
                                                         :locale => SUPPORTED_LOCALES,
                                                         :branch => SUPPORTED_BRANCHES

# TODO: drop this later
##  get '/repocop' => 'repocop#index'
##  get '/repocop/by-test/:testname' => 'repocop#bytest'
#
#  get '/repocop/by-test/install_s' => 'repocop#srpms_install_s'

  # TODO: drop this and make API
  get '/repocop/no_url_tag' => 'repocop#no_url_tag'
  get '/repocop/invalid_url' => 'repocop#invalid_url'
  get '/repocop/invalid_vendor' => 'repocop#invalid_vendor'
  get '/repocop/invalid_distribution' => 'repocop#invalid_distribution'
  get '/repocop/srpms_summary_too_long' => 'repocop#srpms_summary_too_long'
  get '/repocop/packages_summary_too_long' => 'repocop#packages_summary_too_long'
  get '/repocop/srpms_summary_ended_with_dot' => 'repocop#srpms_summary_ended_with_dot'
  get '/repocop/packages_summary_ended_with_dot' => 'repocop#packages_summary_ended_with_dot'
  get '/repocop/srpms_filename_too_long_for_joliet' => 'repocop#srpms_filename_too_long_for_joliet'
  get '/repocop/packages_filename_too_long_for_joliet' => 'repocop#packages_filename_too_long_for_joliet'
  get '/repocop/srpms_install_s' => 'repocop#srpms_install_s'
  # END

  get '/src\::name' => redirect("/en/Sisyphus/srpms/%{name}"), :name => /[^\/]+/
  get '/:name' => 'redirector#index', :name => /[^\/]+/
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @branch = Branch.where(name: params[:branch], vendor: 'ALT Linux').first
    @branches = Branch.order('order_id').all
    if params[:query].nil? || params[:query].empty?
      redirect_to controller: 'home', action: 'index'
    else
      @srpms = Srpm.search(Riddle::Query.escape(params[:query]),
                           :order => :name,
                           :max_matches => 10_000,
                           :per_page => 10_000,
                           :with => { :branch_id => @branch.id },
                           :include => :branch)
      redirect_to(srpm_path(@branch, @srpms.first), status: 302) if @srpms.count == 1
    end
  rescue Mysql2::Error
    render 'search_is_not_available'
  end
end

app/views/searches/search_is_not_available.html.erb
<% title _('Prometheus 2.0 - Search') %>

<div id="main-content">
  <div class="header"><%= _('Search is not available.') %></div>
  <span class="news-text">
    <%= _('Sphinx rebuild indexes. Please try again later.') %>
  </span>
</div>

<div id="bottom-offset-l">
  <div id="bottom-offset-r">
    &nbsp;
  </div>
</div>

app/views/searches/show.html.erb
<% title _('Prometheus 2.0 - Search') %>

<div id="main-content">

  <div class="header" style="letter-spacing: 1px;"><%= _('Search') %></div>
  <p class="break"></p>
  <%= form_tag search_path(branch: @branch.name), method: :get do %>
    <%= select_tag :branch, options_from_collection_for_select(@branches, 'name', 'name', @branch.name) %>
    <%= text_field_tag :query, params[:query] ? params[:query] : 'Search...', size: '20', 'x-webkit-speech' => '' %>
    <%= submit_tag 'Search', name: nil, class: 'top-go', id: 'subOn', value: _('find'), onmouseover: "m_on('subOn')", onmouseout: "m_off('subOn')" %>
  <% end %>

  <br>
  <br>
  <%= _('On your query &quot;').html_safe %><b><%= params[:query] %></b>
  <%= (_('&quot; in branch <b>%s</b> were found') % @branch.name).html_safe %>
  <b><%= @srpms.total_entries %></b>
  <%= n_('RPM:', 'RPMs:', @srpms.total_entries) %>

  <p class="break"></p>
  <br>
  <table id='bugs' cellspacing='0' cellpadding='3'>
    <tr>
      <% if @branch.name == 'Sisyphus' %>
        <th><%= raw _('repo<br>cop') %></th>
      <% end %>
      <th><%= _('package') %></th>
      <th><%= raw _('current<br>version') %></th>
      <th><%= _('build time') %></th>
      <th><%= _('age') %></th>
      <th><%= _('Url') %></th>
      <th><%= _('summary') %></th>
    </tr>

    <% @srpms.each do |srpm| %>
      <% if srpm %>
        <tr>
          <% if @branch.name == 'Sisyphus' %>
            <td>
              <%= link_to image_tag("#{srpm.repocop}.png", size: '20x20', alt: srpm.repocop), repocop_srpm_path(srpm), class: 'repocoplink', title: _('repocop') %>
            </td>
          <% end %>
          <td class="strange">
            <%= link_to srpm.name, srpm_path(srpm.branch, srpm), class: 'news' %>
          </td>
          <td><%= "#{srpm.version}-#{srpm.release}" %></td>
          <td><%= srpm.buildtime %></td>
          <td><%= "#{time_ago_in_words(srpm.buildtime)} #{_('ago')}" %></td>
          <td><%= srpm.decorate.short_url %></td>
          <td><%= srpm.summary %></td>
        </tr>
      <% end %>
    <% end %>
  </table>

<div id="bottom-offset-l">
  <div id="bottom-offset-r">
    &nbsp;
  </div>
</div>